name: C/C++ CI

on:
  push:
    branches: [ "master", "gh_893" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: make prep
      run: make prep
    - name: make test
      run: make test
    - name: make clobber
      run: make clobber
